name: atlas

# map from output proposition (of a state) to output for entire SM
output:
    finished: finished

pickup_a:
    class_decl: GraspObjectSM()
    output_mapping:
        pickup_c: changed
        failed : failed
    autonomy: LOW
manipulate_a:
    class_decl: ChangeControlModeActionState(ChangeControlModeActionState.MANIPULATE)
    output_mapping:
        manipulate_c: changed
        failed : failed
    autonomy: LOW
stand_prep_a:
    class_decl: ChangeControlModeActionState(ChangeControlModeActionState.STAND_PREP)
    output_mapping:
        stand_prep_c: changed
        failed : failed
    autonomy: LOW
stand_a:
    class_decl: ChangeControlModeActionState(ChangeControlModeActionState.STAND)
    output_mapping:
        stand_c: changed
        failed : failed
    autonomy: LOW
step_a:
    class_decl: ChangeControlModeActionState(ChangeControlModeActionState.STEP)
    output_mapping:
        step_c: changed
        failed : failed
    autonomy: LOW
walk_a:
    class_decl: ChangeControlModeActionState(ChangeControlModeActionState.WALK)
    output_mapping:
        walk_c: changed
        failed : failed
    autonomy: LOW
obj_detected:
    class_decl: SensorReading
    output_mapping:
        obj_detected: found
    autonomy: LOW
