name: atlas

# Mapping from output propositions to outputs of the State Machine
output:
    finished: finished
    failed: failed

# Mapping from activation propositions to parametrized states and their outcomes
pickup_a:
    class_decl:
        name: ExecuteTrajectoryMsgState
        param_names:
            - controller
        param_values:
            - ExecuteTrajectoryMsgState.CONTROLLER_LEFT_ARM
    output_mapping:
        pickup_c: done
        pickup_f : failed
    autonomy: 0
grasp_a:
    class_decl:
        name: GraspObjectSM
        param_names: []
        param_values: []
    output_mapping:
        grasp_c: finished
        grasp_f : failed
    autonomy: 0
approach_object_a:
    class_decl:
        name: WalktoTemplateSM
        param_names: []
        param_values: []
    output_mapping:
        approach_object_c: finished
        approach_object_f : failed
    autonomy: 0
manipulate_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.MANIPULATE
    output_mapping:
        manipulate_c: changed
        manipulate_f : failed
    autonomy: 0
stand_prep_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.STAND_PREP
    output_mapping:
        stand_prep_c: changed
        stand_prep_f : failed
    autonomy: 0
stand_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.STAND
    output_mapping:
        stand_c: changed
        stand_f : failed
    autonomy: 0
step_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.STEP
    output_mapping:
        step_c: changed
        step_f : failed
    autonomy: 0
walk_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.WALK
    output_mapping:
        walk_c: changed
        walk_f : failed
    autonomy: 0
obj_detected:
    class_decl:
        name: SensorReading
        param_names: []
        param_values: []
    output_mapping:
        obj_detected: found
    autonomy: 0
