name: atlas

# Mapping from output propositions to outputs of the State Machine
output:
    finished: finished
    failed: failed

# Mapping from activation propositions to parametrized states and their outcomes
pickup_a:
    class_decl:
        name: ExecuteTrajectoryMsgState
        param_names:
            - controller
        param_values:
            - ExecuteTrajectoryMsgState.CONTROLLER_LEFT_ARM
    output_mapping:
        pickup_c: [done]
        pickup_f: [failed]
    autonomy: 0
grasp_a:
    class_decl:
        name: GraspObjectSM
        param_names: []
        param_values: []
    output_mapping:
        grasp_c: [finished]
        grasp_f: [failed]
    autonomy: 0
approach_object_a:
    class_decl:
        name: WalktoTemplateSM
        param_names: []
        param_values: []
    output_mapping:
        approach_object_c: [finished]
        approach_object_f: [failed, aborted]
    autonomy: 0
target_pose_a:
    class_decl:
        name: InputState
        param_names:
            - request
            - message
        param_values:
            - InputState.WAYPOINT_GOAL_POSE
            - '"Please provide a footsteps pose"'
    output_mapping:
        target_pose_c: [received]
        target_pose_f: [aborted, no_connection, data_error]
    autonomy: 0
    userdata_keys: [data]
    userdata_remapping: [step_goal]
footstep_goal_a:
    class_decl:
        name: CreateStepGoalState
        param_names:
            - pose_is_pelvis
        param_values:
            - 'False'
    output_mapping:
        footstep_goal_c: [done]
        footstep_goal_f: [failed]
    autonomy: 0
footstep_plan_a:
    class_decl:
        name: PlanFootstepsState
        param_names:
            - mode
        param_values:
            - PlanFootstepsState.MODE_STEP_2D
    output_mapping:
        footstep_plan_c: [planned]
        footstep_plan_f: [failed]
    autonomy: 0
footstep_execution_a:
    class_decl:
        name: ExecuteStepPlanActionState
        param_names: []
        param_values: []
    output_mapping:
        footstep_execution_c: [finished]
        footstep_execution_f: [failed]
    autonomy: 0
manipulate_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.MANIPULATE
    output_mapping:
        manipulate_c: [changed]
        manipulate_f: [failed]
    autonomy: 0
stand_prep_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.STAND_PREP
    output_mapping:
        stand_prep_c: [changed]
        stand_prep_f: [failed]
    autonomy: 0
stand_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.STAND
    output_mapping:
        stand_c: [changed]
        stand_f: [failed]
    autonomy: 0
step_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.STEP
    output_mapping:
        step_c: [changed]
        step_f: [failed]
    autonomy: 0
walk_a:
    class_decl:
        name: ChangeControlModeActionState
        param_names:
            - target_mode
        param_values:
            - ChangeControlModeActionState.WALK
    output_mapping:
        walk_c: [changed]
        walk_f: [failed]
    autonomy: 0
obj_detected:
    class_decl:
        name: SensorReading
        param_names: []
        param_values: []
    output_mapping:
        obj_detected: [found]
    autonomy: 0
