# Control Mode transition system
transition_system:
    stand_prep:
        - stand_prep
        - stand
    stand:
        - stand_prep
        - stand
        - manipulate
        - step
        - walk
    manipulate:
        - manipulate
        - stand
    step:
        - step
        - stand
    walk:
        - walk
        - stand

# Action Pre-conditions (ATLAS and ViGIR software specific)
action_preconditions:
    pickup:
        - grasp
        - manipulate
    grasp:
        - approach_object
        - manipulate
    approach_object:
        - stand
    footstep_execution:
        - footstep_plan
        - stand
    footstep_plan:
        - footstep_goal
    footstep_goal:
        - target_pose
    target_pose: []
